### ISSUE TITLE
net-libs/restbed-9999 used bundled lib instead of system.

### ISSUE THREAD

**Issue by YogSottot** [reagentoo/gentoo-overlay#1]
In its current condition, restbed used bundled lib instead of system.
```bash
-- Found ASIO include at: /var/tmp/portage/net-libs/restbed-9999/work/restbed-9999/dependency/asio/asio/include
-- Found Kashmir include at: /var/tmp/portage/net-libs/restbed-9999/work/restbed-9999/dependency/kashmir
```
You can use [my patch](https://github.com/YogSottot/ring-overlay/blob/restbed_live_update/net-libs/restbed/files/Change-detecting-libs-to-system.patch) or sed or whatever to fix it.

p.s.
Btw, you really should try 'repoman full' to check your overlay.

**Comment by reagentoo** [comment]
#https://github.com/reagentoo/gentoo-overlay/commit/38c1aaac6c163b514be0538accd230a0c1db58b6
Just git submodules disabled now.
