### ISSUE TITLE
net-im/telegram-desktop-9999 build failed

### ISSUE THREAD

**Issue by eegorov** [reagentoo/gentoo-overlay#10]
`[  4%] Building C object ThirdParty/libtgvoip/webrtc_dsp/webrtc/CMakeFiles/webrtc.dir/common_audio/signal_processing/auto_correlation.c.o
cd /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999_build/ThirdParty/libtgvoip/webrtc_dsp/webrtc && /usr/bin/x86_64-pc-linux-gnu-gcc -DWEBRTC_APM_DEBUG_DUMP=0 -DWEBRTC_POSIX -I/mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999_build/ThirdParty/libtgvoip/webrtc_dsp/webrtc -I/mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/libtgvoip/webrtc_dsp/webrtc -I/mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999_build/ThirdParty/libtgvoip/webrtc_dsp/webrtc/webrtc_autogen/include -I/mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/libtgvoip/webrtc_dsp/webrtc/..   -DNDEBUG -O2 -pipe -march=native   -o CMakeFiles/webrtc.dir/common_audio/signal_processing/auto_correlation.c.o -c /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/libtgvoip/webrtc_dsp/webrtc/common_audio/signal_processing/auto_correlation.c
In file included from /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/common/crl_common_list.cpp:8:0:
/mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/common/crl_common_list.h:85:35: error: use of deleted function 'std::atomic<_Tp*>::atomic(const std::atomic<_Tp*>&) [with _Tp = crl::details::list::BasicEntry]'
  std::atomic<BasicEntry*> _head = nullptr;
                                   ^~~~~~~
In file included from /usr/include/qt5/QtCore/qatomic_cxx11.h:45:0,
                 from /usr/include/qt5/QtCore/qbasicatomic.h:53,
                 from /usr/include/qt5/QtCore/qatomic.h:46,
                 from /usr/include/qt5/QtCore/qglobal.h:1158,
                 from /usr/include/qt5/QtCore/qsemaphore.h:43,
                 from /usr/include/qt5/QtCore/QSemaphore:1,
                 from /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/qt/crl_qt_semaphore.h:15,
                 from /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/crl_semaphore.h:17,
                 from /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/common/crl_common_list.h:19,
                 from /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/common/crl_common_list.cpp:8:
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/atomic:332:7: note: declared here
       atomic(const atomic&) = delete;
       ^~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/include/g++-v6/atomic:336:17: note:   after user-defined conversion: constexpr std::atomic<_Tp*>::atomic(std::atomic<_Tp*>::__pointer_type) [with _Tp = crl::details::list::BasicEntry; std::atomic<_Tp*>::__pointer_type = crl::details::list::BasicEntry*]
       constexpr atomic(__pointer_type __p) noexcept : _M_b(__p) { }
                 ^~~~~~
In file included from /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/common/crl_common_list.cpp:8:0:
/mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/common/crl_common_list.h: In static member function 'static void crl::details::list::Entry<Function>::Process(crl::details::list::BasicEntry*)':
/mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/ThirdParty/crl/src/crl/common/crl_common_list.h:64:17: error: 'finally' is not a member of 'crl::details'
    auto guard = details::finally([=] { delete full; });
                 ^~~~~~~
make[2]: *** [ThirdParty/crl/CMakeFiles/crl.dir/build.make:63: ThirdParty/crl/CMakeFiles/crl.dir/src/crl/common/crl_common_list.cpp.o] Error 1
make[2]: Leaving directory '/mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999_build'
make[1]: *** [CMakeFiles/Makefile2:549: Third`

**Comment by eegorov** [comment]
# wgetpaste /mnt/localrep/tmp/portage/net-im/telegram-desktop-9999/temp/build.log
Your paste can be seen here: https://paste.pound-python.org/show/gmnvyk7fXD8S7co2rwbb/

**Comment by reagentoo** [comment]
At least gcc 7.0 is required.
Added check in pkg_pretend: https://github.com/reagentoo/gentoo-overlay/commit/16a0a595a65023cdcf528c8d075b3276690fbca5
