### ISSUE TITLE
net-im/telegram-desktop cmake licensing?

### ISSUE THREAD

**Issue by Johnnynator** [reagentoo/gentoo-overlay#17]
Hi,

should the telegram-desktop cmake scripts be considered to be under the same license as telegram-desktop ( GPL-3.0-or-later-with-openssl-exception ) or under GPL-2.0 like the ebuilds?

Also the ebuild/cmake will not build telegram-desktop for x86 since the `-msse2` CFLAG is probably missing and also `-DQ_OS_LINUX64` is set always instead of `-DQ_OS_LINUX32` for x86 .

**Comment by reagentoo** [comment]
You can use it anywhere. It's opensource.

If you are realy interested in building a package on Gentoo ~x86 please test your changes in local overlay and make PR.

**Comment by Johnnynator** [comment]
> If you are realy interested in building a package on Gentoo ~x86 please test your changes in local overlay and make PR.

My Comment regarding was only informative, since , I don't use a x86 Gentoo system.
> You can use it anywhere. It's opensource.

Mkay. So I can just add it to a telegram-desktop fork without any further licensing mentionings.
