### ISSUE TITLE
telegram-desktop-1.3.10: gcc-if-constexpr-tmpfix.patch outdated

### ISSUE THREAD

**Issue by adrianopol** [reagentoo/gentoo-overlay#19]
Error: https://bugs.gentoo.org/662114.

Curent patch version: https://github.com/Johnnynator/void-packages/blob/7b4f0a0c832eb9ca56b316d39a111669be77d27d/srcpkgs/telegram-desktop/patches/gcc-if-constexpr-tmpfix.patch.

Tested (with small modification) on https://github.com/adrianopol/paq-overlay/tree/master/net-im/telegram-desktop.

**Comment by reagentoo** [comment]
Maybe you will provide more information?
- which version affected
- which version not affected

... what is a void-packages?

**Comment by adrianopol** [comment]
1.3.10 is affected; 1.3.9 has been compiled normally.

The first link is the description of the bug: it is a gcc bug, that was fixed in gcc-7.3.1, which is currently not present in gentoo packages, so you use gcc-if-constexpr-tmpfix.patch. But this patch is not a suitable fix for building 1.3.10. Version from void-packages repository is an appropriate fix for 1.3.10.

void-packages is a part of some GNU/Linux distribution.

**Comment by adrianopol** [comment]
```
[ebuild   R   #] net-im/telegram-desktop-1.4.4::reagentoo [1.4.4::mva] USE="pulseaudio -crashreporter% -custom-api-id -debug -gtk3* -test% (-crash-report%) (-libressl%) (-wide-baloons%)" 0 KiB
...
/var/tmp/portage/net-im/telegram-desktop-1.4.4/work/telegram-desktop-1.4.4/Telegram/SourceFiles/export/export_api_wrap.cpp: In lambda function:
/var/tmp/portage/net-im/telegram-desktop-1.4.4/work/telegram-desktop-1.4.4/Telegram/SourceFiles/export/export_api_wrap.cpp:723:56: internal compiler error: Segmentation fault
   if constexpr (MTPDphotos_photos::Is<decltype(data)>()) {
```

```
[I] sys-devel/gcc
...
     Installed versions:  7.3.0-r3(7.3.0)^s(01:29:24 AM 08/23/2018)(cxx fortran go multilib nls nptl openmp pch pie sanitize ssp vtv -altivec -cilk -debug -doc -fixed-point -graphite -hardened -jit -libssp -mpx -objc -objc++ -objc-gc -pgo -regression-test -vanilla)
```

**Comment by reagentoo** [comment]
`eselect gcc list`

**Comment by reagentoo** [comment]
Check it please: https://github.com/reagentoo/gentoo-overlay/commit/26a56933968d74ece151d9bd997db5347b11e4d3

**Comment by adrianopol** [comment]
> Check it please: [26a5693](https://github.com/reagentoo/gentoo-overlay/commit/26a56933968d74ece151d9bd997db5347b11e4d3)

Yes, it compiles.
