### ISSUE TITLE
webcamoid missing dependancies

### ISSUE THREAD

**Issue by mathroc** [reagentoo/gentoo-overlay#2]
* dev-qt/qtconcurrent
* dev-qt/qtsvg
* dev-qt/qtquickcontrols

otherwise you got, respectively, those errors :

* > Project ERROR: Unknown module(s) in QT: concurrent
* > Project ERROR: Unknown module(s) in QT: svg
* at runtime: 
  > qrc:/Webcamoid/share/qml/main.qml:23 module "QtQuick.Controls" is not installed
  qrc:/Webcamoid/share/qml/main.qml:21 module "QtQuick.Dialogs" is not installed

**Comment by reagentoo** [comment]
Thanks.
#https://github.com/reagentoo/gentoo-overlay/commit/048e53c8afc1549127a2aad4349862b7da319d20
