### ISSUE TITLE
srain is old

### ISSUE THREAD

**Issue by okias** [reagentoo/gentoo-overlay#25]
check https://github.com/okias/ixit/commit/f03355ab945b63a11343c156bef87f1a5c963876 also modernize or drop -9999  :)

**Comment by reagentoo** [comment]
thanks https://github.com/reagentoo/gentoo-overlay/commit/146ccb5dbe3c6719e67508bdcabc0a609b976d8f

**Comment by okias** [comment]
np, also don't forget run repoman full before committing, you'll notice some unsolved issues.
