### ISSUE TITLE
=net-p2p/ethminer-0.11.0 started with wrong CXXFLAGS

### ISSUE THREAD

**Issue by maxbleatvt** [reagentoo/gentoo-overlay#3]
I'm no expert, so I'm not sure if there's a misconfiguration on my end, but your ebuild doesn't start with C++11 support enabled for ethminer. (Apparently it uses C++11 features?)
CXXFLAGS="-std=c++11" emerge -av =net-p2p/ethminer-0.11.0::reagentoo"
These allowed your ebuild to build for me

**Comment by reagentoo** [comment]
Need more info about your system: GCC version, accepted keywords. emerge --info ethminer, build.log desirable.

**Comment by maxbleatvt** [comment]
[emerge --info ethminer](https://github.com/reagentoo/gentoo-overlay/files/1171638/EmergeInfo.txt)
[make.conf.txt](https://github.com/reagentoo/gentoo-overlay/files/1171640/make.conf.txt)
[build.log.txt](https://github.com/reagentoo/gentoo-overlay/files/1171641/build.log.txt)
These are all with CXXFLAGS="-std=c++11", allowing ethminer to build. my gcc is 5.4.0-r3

[emerge --info](https://github.com/reagentoo/gentoo-overlay/files/1171643/EmergeInfoNormal.txt)
These are my normal flags

**Comment by reagentoo** [comment]
Please, try fixed and tell about result.
#https://github.com/reagentoo/gentoo-overlay/commit/857cec2975534a79d6157c480195031aaa522f90
